### PR TITLE
Cryptography

### LINKED ISSUE #47: [Cryptographer] / [Can encrypt and decrypt all the text in a document and stores in a new file]
- [x] Create a folder in the Projects Folder with the name of your project - Cryptographer
- [x] Create a README.md file describing your project briefly

I will do all the necessary things and will create a pull request.. Please accept this for hacktober fest..

### PR DESCRIPTION
**Pull request by CapedDemon**
## Fixes Issue
#47 
Closes
#47 
Hey I have made cyptographer with proper readme. Please check it.

## Changes proposed
[x] - Cryptographer- A python script to encrypt and decrypt files

## Check List (Check all the applicable boxes) 

- [x] I have updated the documentation accordingly.
- [x] I have added a new Project.
- [x] I have added a README.md file for the Project.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by sree-hari-s** [comment]
image

Not working for me , am I doing anything wrong?

**Comment by CapedDemon** [comment]
ok one solution - 
You first need to close the text editor.
Go to the folder 
open terminal/cmd there
close any other text editor
create the testing.txt with notepad
enter hello world
save and close the note pad other text editors 
you can do it in vs code but close it after writing.
then do the thing in cmd/terminal but not in vscode terminal

**Comment by sree-hari-s** [comment]
> ok one solution - You first need to close the text editor. Go to the folder open terminal/cmd there close any other text editor create the testing.txt with notepad enter hello world save and close the note pad other text editors you can do it in vs code but close it after writing. then do the thing in cmd/terminal but not in vscode terminal

none of the text files were open while I was running the application, I just opened it up for taking the screenshot.

**Comment by CapedDemon** [comment]
Try another time in different folder freshly. I am preparing a video for help please wait for it

**Comment by sree-hari-s** [comment]
> Try another time in different folder freshly. I am preparing a video for help please wait for it

Yeah when I checked now its working 😁, IDK what went wrong earlier.

**Comment by CapedDemon** [comment]
Yeah great

**Pull request merged**
