### PR TITLE
new pull request

### PR DESCRIPTION
**Pull request by avimoti1234**

### CODE REVIEW

**Comment by sree-hari-s** [comment]
are you not able to see 50 changed files?

**Review by sree-hari-s — APPROVED** [review]

**Comment by sree-hari-s** [comment]
Next time pull the latest code before working.

**Comment by sree-hari-s** [comment]
sorry seems to have lot of issues

**Comment by avimoti1234** [comment]
what issues do you encounter? I do not have any issues running it

**Comment by sree-hari-s** [comment]
issue is not in your code but issue arises because you have changed other files

**Comment by sree-hari-s** [comment]
if you are using git bash dont do `git add .` instead manually add the files you have modified only

**Comment by avimoti1234** [comment]
OK so I will clone the repository again and just add the code the I have written

**Comment by sree-hari-s** [comment]
yes try that way

**Pull request merged**
