### PR TITLE
feat: Create a Hangman game using Python

### PR DESCRIPTION
**Pull request by purnasth**
## Check List (Check all the applicable boxes) 

- [x] I have updated the documentation accordingly.
- [X] I have added a new Project.
- [X] I have added a README.md file for the Project.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots

hangman

### CODE REVIEW

**Comment by sree-hari-s** [comment]
image
Even after getting the whole word correctly the game didn't conclude.

Also it would be nice to showcase a hangman in ascii art instead of showing remaining lives.
[Refer this file](https://github.com/sree-hari-s/MasteringPyTrail/blob/master/100DaysofCode/Beginner/Day-7-Hangman/Hangman%20Final%20Game/hangman_art.py)

**Comment by purnasth** [comment]
image
image
image
image

**Comment by purnasth** [comment]
Hello, I've applied the ASCII art to this hangman project, and the project is ready to be merged.

**Comment by sree-hari-s** [comment]
Thankyou for your contribution, Please leave a 🌟 and also try to contribute more of your work.

**Pull request merged**
