### PR TITLE
New project | Flask form

### LINKED ISSUE #29: [PROJECT] Flask Projects
- [ ] Create a folder in the Projects Folder with the name of your project
- [ ] Create a README.md file describing your project briefly

### PR DESCRIPTION
**Pull request by Zedeldi**
## Fixes Issue

Closes #29.

## Changes proposed

- [X] I have updated the documentation accordingly.
- [X] I have added a new Project.
- [X] I have added a README.md file for the Project.
- [X] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Zedeldi** [comment]
I believe this is due to the repo and main branch changing names, after I created my fork. Only the new project files will be added with a merge, but I can make a new fork if required.

**Comment by sree-hari-s** [comment]
Oh is it can please do that so

**Comment by Zedeldi** [comment]
I reset my branch to upstream `master`, then re-committed my changes.
Should just be one commit now - thanks.

**Review by sree-hari-s — CHANGES_REQUESTED** [review]
This project is good but can you just include some styles , as it is almost like the first project.

**Comment by sree-hari-s** [comment]
> I've added [Bootstrap](https://getbootstrap.com/) CSS to the page, which shows how styles and static files are handled too.

Thankyou for updating. Great work.

**Pull request merged**
