### PR TITLE
Added a Django Project

### LINKED ISSUE #28: [PROJECT] Django Projects
- [ ] Create a folder in the Projects Folder with the name of your project
- [ ] Create a README.md file describing your project briefly

### LINKED ISSUE #31: [PROJECT] / [PROJECT IDEA]
I can add a an aim trainer for the intermidiate.

### PR DESCRIPTION
**Pull request by Virtual4087**
Closes #28 

## Check List (Check all the applicable boxes) 

- [x ] I have updated the documentation accordingly.
- [ x] I have added a new Project.
- [x ] I have added a README.md file for the Project.
- [x ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Virtual4087** [comment]
My bad i'll hide it

**Comment by Virtual4087** [comment]
any idea why's it still showing failed? I changed the django secret key to a github secret variable

**Comment by sree-hari-s** [comment]
> any idea why's it still showing failed? I changed the django secret key to a github secret variable

no idea can you raise a new PR

**Comment by Virtual4087** [comment]
ok

**Comment by Virtual4087** [comment]
I'll close this one and open another pr

**Pull request closed without merging**
