### PR TITLE
Anaemia Detection - ML Project

### PR DESCRIPTION
**Pull request by nehareddies**
## Changes proposed

Have added in a project on Anaemia Detection to ML projects. A contribution to Hacktoberfest!

## Check List (Check all the applicable boxes) 

- [x] I have updated the documentation accordingly.
- [x] I have added a new Project.
- [x] I have added a README.md file for the Project.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
image

### CODE REVIEW

**Comment by sree-hari-s** [comment]
image

Can you help me fix this error?

**Comment by nehareddies** [comment]
> image
> 
> Can you help me fix this error?

Oh, Ill figure out on the issue, But I have added the main prediction part in ML Projects.
Looking forward to seek approval on that part
Sorry for the inconvenience caused

**Comment by sree-hari-s** [comment]
Can you also add a short description in a markdown file `Readme.md` about your project. So anyone could get an idea about the project.

**Comment by nehareddies** [comment]
Hey, There was a small issue. I have updated both the notebook and the readme file now.

**Comment by nehareddies** [comment]
Let me know if any other changes. If not requesting you to add the hacktoberfest label...

**Pull request merged**
